# ===============================
# Swarm Simulator Configuration
# See: sim_server/src/config.rs for full schema
# ===============================

arena:
  # Minimum corner of the arena (x, y, z)
  min: [-10.0, -10.0, -10.0]
  # Maximum corner of the arena (x, y, z)
  max: [10.0, 10.0, 10.0]
  # Minimum distance between drones when randomizing start pos. [m]
  min_dist: 2
  randomize_init_pos: true
  cell_size: 20

target:
  enabled: false
  position: [0.0, 0.0, 0.0]
  radius: 0.1

physics:
  # Fixed simulation timestep [seconds]
  dt: 0.02
  # Maximum allowed velocity magnitude
  max_velocity: 10.0

sensing:
  # Max sensing distance, has to be smaller than 2*cell_size
  max_sensing: 50.0


collisions:
  # Collision radius per drone
  radius: 0.5

team_1_controller:
  # Enable simulator-owned drones, only used if there are team 1 drones
  enabled: true
  # Behavior name (mapped internally in simulator)
  behavior: "straight_flying"
  init_pos_center: [16.0, 0.0, 0.0]
  
logging:
  # Enable episode logging
  enabled: true
  # Enable profiling
  profiling_enabled: false
  profiling_frequency: 1000 # Hz