// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: swarm.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_swarm_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_swarm_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_swarm_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_swarm_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_swarm_2eproto;
namespace swarm_proto {
class DroneAction;
struct DroneActionDefaultTypeInternal;
extern DroneActionDefaultTypeInternal _DroneAction_default_instance_;
class DroneObservation;
struct DroneObservationDefaultTypeInternal;
extern DroneObservationDefaultTypeInternal _DroneObservation_default_instance_;
class ResetRequest;
struct ResetRequestDefaultTypeInternal;
extern ResetRequestDefaultTypeInternal _ResetRequest_default_instance_;
class ResetResponse;
struct ResetResponseDefaultTypeInternal;
extern ResetResponseDefaultTypeInternal _ResetResponse_default_instance_;
class StepRequest;
struct StepRequestDefaultTypeInternal;
extern StepRequestDefaultTypeInternal _StepRequest_default_instance_;
class StepResponse;
struct StepResponseDefaultTypeInternal;
extern StepResponseDefaultTypeInternal _StepResponse_default_instance_;
}  // namespace swarm_proto
PROTOBUF_NAMESPACE_OPEN
template<> ::swarm_proto::DroneAction* Arena::CreateMaybeMessage<::swarm_proto::DroneAction>(Arena*);
template<> ::swarm_proto::DroneObservation* Arena::CreateMaybeMessage<::swarm_proto::DroneObservation>(Arena*);
template<> ::swarm_proto::ResetRequest* Arena::CreateMaybeMessage<::swarm_proto::ResetRequest>(Arena*);
template<> ::swarm_proto::ResetResponse* Arena::CreateMaybeMessage<::swarm_proto::ResetResponse>(Arena*);
template<> ::swarm_proto::StepRequest* Arena::CreateMaybeMessage<::swarm_proto::StepRequest>(Arena*);
template<> ::swarm_proto::StepResponse* Arena::CreateMaybeMessage<::swarm_proto::StepResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace swarm_proto {

// ===================================================================

class DroneAction final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:swarm_proto.DroneAction) */ {
 public:
  inline DroneAction() : DroneAction(nullptr) {}
  ~DroneAction() override;
  explicit PROTOBUF_CONSTEXPR DroneAction(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DroneAction(const DroneAction& from);
  DroneAction(DroneAction&& from) noexcept
    : DroneAction() {
    *this = ::std::move(from);
  }

  inline DroneAction& operator=(const DroneAction& from) {
    CopyFrom(from);
    return *this;
  }
  inline DroneAction& operator=(DroneAction&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DroneAction& default_instance() {
    return *internal_default_instance();
  }
  static inline const DroneAction* internal_default_instance() {
    return reinterpret_cast<const DroneAction*>(
               &_DroneAction_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DroneAction& a, DroneAction& b) {
    a.Swap(&b);
  }
  inline void Swap(DroneAction* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DroneAction* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DroneAction* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DroneAction>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DroneAction& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DroneAction& from) {
    DroneAction::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DroneAction* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "swarm_proto.DroneAction";
  }
  protected:
  explicit DroneAction(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAxFieldNumber = 1,
    kAyFieldNumber = 2,
    kAzFieldNumber = 3,
  };
  // float ax = 1;
  void clear_ax();
  float ax() const;
  void set_ax(float value);
  private:
  float _internal_ax() const;
  void _internal_set_ax(float value);
  public:

  // float ay = 2;
  void clear_ay();
  float ay() const;
  void set_ay(float value);
  private:
  float _internal_ay() const;
  void _internal_set_ay(float value);
  public:

  // float az = 3;
  void clear_az();
  float az() const;
  void set_az(float value);
  private:
  float _internal_az() const;
  void _internal_set_az(float value);
  public:

  // @@protoc_insertion_point(class_scope:swarm_proto.DroneAction)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float ax_;
    float ay_;
    float az_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_swarm_2eproto;
};
// -------------------------------------------------------------------

class DroneObservation final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:swarm_proto.DroneObservation) */ {
 public:
  inline DroneObservation() : DroneObservation(nullptr) {}
  ~DroneObservation() override;
  explicit PROTOBUF_CONSTEXPR DroneObservation(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DroneObservation(const DroneObservation& from);
  DroneObservation(DroneObservation&& from) noexcept
    : DroneObservation() {
    *this = ::std::move(from);
  }

  inline DroneObservation& operator=(const DroneObservation& from) {
    CopyFrom(from);
    return *this;
  }
  inline DroneObservation& operator=(DroneObservation&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DroneObservation& default_instance() {
    return *internal_default_instance();
  }
  static inline const DroneObservation* internal_default_instance() {
    return reinterpret_cast<const DroneObservation*>(
               &_DroneObservation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DroneObservation& a, DroneObservation& b) {
    a.Swap(&b);
  }
  inline void Swap(DroneObservation* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DroneObservation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DroneObservation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DroneObservation>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DroneObservation& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DroneObservation& from) {
    DroneObservation::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DroneObservation* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "swarm_proto.DroneObservation";
  }
  protected:
  explicit DroneObservation(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOxFieldNumber = 1,
    kOyFieldNumber = 2,
    kOzFieldNumber = 3,
    kCollisionCountFieldNumber = 4,
  };
  // float ox = 1;
  void clear_ox();
  float ox() const;
  void set_ox(float value);
  private:
  float _internal_ox() const;
  void _internal_set_ox(float value);
  public:

  // float oy = 2;
  void clear_oy();
  float oy() const;
  void set_oy(float value);
  private:
  float _internal_oy() const;
  void _internal_set_oy(float value);
  public:

  // float oz = 3;
  void clear_oz();
  float oz() const;
  void set_oz(float value);
  private:
  float _internal_oz() const;
  void _internal_set_oz(float value);
  public:

  // uint32 collision_count = 4;
  void clear_collision_count();
  uint32_t collision_count() const;
  void set_collision_count(uint32_t value);
  private:
  uint32_t _internal_collision_count() const;
  void _internal_set_collision_count(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:swarm_proto.DroneObservation)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float ox_;
    float oy_;
    float oz_;
    uint32_t collision_count_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_swarm_2eproto;
};
// -------------------------------------------------------------------

class StepRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:swarm_proto.StepRequest) */ {
 public:
  inline StepRequest() : StepRequest(nullptr) {}
  ~StepRequest() override;
  explicit PROTOBUF_CONSTEXPR StepRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StepRequest(const StepRequest& from);
  StepRequest(StepRequest&& from) noexcept
    : StepRequest() {
    *this = ::std::move(from);
  }

  inline StepRequest& operator=(const StepRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StepRequest& operator=(StepRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StepRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const StepRequest* internal_default_instance() {
    return reinterpret_cast<const StepRequest*>(
               &_StepRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(StepRequest& a, StepRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(StepRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StepRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StepRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StepRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StepRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StepRequest& from) {
    StepRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StepRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "swarm_proto.StepRequest";
  }
  protected:
  explicit StepRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kActionsFieldNumber = 2,
    kStepFieldNumber = 1,
  };
  // repeated .swarm_proto.DroneAction actions = 2;
  int actions_size() const;
  private:
  int _internal_actions_size() const;
  public:
  void clear_actions();
  ::swarm_proto::DroneAction* mutable_actions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::swarm_proto::DroneAction >*
      mutable_actions();
  private:
  const ::swarm_proto::DroneAction& _internal_actions(int index) const;
  ::swarm_proto::DroneAction* _internal_add_actions();
  public:
  const ::swarm_proto::DroneAction& actions(int index) const;
  ::swarm_proto::DroneAction* add_actions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::swarm_proto::DroneAction >&
      actions() const;

  // uint64 step = 1;
  void clear_step();
  uint64_t step() const;
  void set_step(uint64_t value);
  private:
  uint64_t _internal_step() const;
  void _internal_set_step(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:swarm_proto.StepRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::swarm_proto::DroneAction > actions_;
    uint64_t step_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_swarm_2eproto;
};
// -------------------------------------------------------------------

class StepResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:swarm_proto.StepResponse) */ {
 public:
  inline StepResponse() : StepResponse(nullptr) {}
  ~StepResponse() override;
  explicit PROTOBUF_CONSTEXPR StepResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StepResponse(const StepResponse& from);
  StepResponse(StepResponse&& from) noexcept
    : StepResponse() {
    *this = ::std::move(from);
  }

  inline StepResponse& operator=(const StepResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline StepResponse& operator=(StepResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StepResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const StepResponse* internal_default_instance() {
    return reinterpret_cast<const StepResponse*>(
               &_StepResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(StepResponse& a, StepResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(StepResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StepResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StepResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StepResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StepResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StepResponse& from) {
    StepResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StepResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "swarm_proto.StepResponse";
  }
  protected:
  explicit StepResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObservationsFieldNumber = 2,
    kStepFieldNumber = 1,
    kRewardFieldNumber = 3,
    kDoneFieldNumber = 4,
  };
  // repeated .swarm_proto.DroneObservation observations = 2;
  int observations_size() const;
  private:
  int _internal_observations_size() const;
  public:
  void clear_observations();
  ::swarm_proto::DroneObservation* mutable_observations(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::swarm_proto::DroneObservation >*
      mutable_observations();
  private:
  const ::swarm_proto::DroneObservation& _internal_observations(int index) const;
  ::swarm_proto::DroneObservation* _internal_add_observations();
  public:
  const ::swarm_proto::DroneObservation& observations(int index) const;
  ::swarm_proto::DroneObservation* add_observations();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::swarm_proto::DroneObservation >&
      observations() const;

  // uint64 step = 1;
  void clear_step();
  uint64_t step() const;
  void set_step(uint64_t value);
  private:
  uint64_t _internal_step() const;
  void _internal_set_step(uint64_t value);
  public:

  // float reward = 3;
  void clear_reward();
  float reward() const;
  void set_reward(float value);
  private:
  float _internal_reward() const;
  void _internal_set_reward(float value);
  public:

  // bool done = 4;
  void clear_done();
  bool done() const;
  void set_done(bool value);
  private:
  bool _internal_done() const;
  void _internal_set_done(bool value);
  public:

  // @@protoc_insertion_point(class_scope:swarm_proto.StepResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::swarm_proto::DroneObservation > observations_;
    uint64_t step_;
    float reward_;
    bool done_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_swarm_2eproto;
};
// -------------------------------------------------------------------

class ResetRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:swarm_proto.ResetRequest) */ {
 public:
  inline ResetRequest() : ResetRequest(nullptr) {}
  ~ResetRequest() override;
  explicit PROTOBUF_CONSTEXPR ResetRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ResetRequest(const ResetRequest& from);
  ResetRequest(ResetRequest&& from) noexcept
    : ResetRequest() {
    *this = ::std::move(from);
  }

  inline ResetRequest& operator=(const ResetRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResetRequest& operator=(ResetRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResetRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResetRequest* internal_default_instance() {
    return reinterpret_cast<const ResetRequest*>(
               &_ResetRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ResetRequest& a, ResetRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ResetRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResetRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResetRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ResetRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ResetRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ResetRequest& from) {
    ResetRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResetRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "swarm_proto.ResetRequest";
  }
  protected:
  explicit ResetRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSeedFieldNumber = 1,
    kMaxStepsFieldNumber = 3,
    kNumDronesFieldNumber = 2,
    kDtFieldNumber = 4,
    kRandomizeInitialPositionsFieldNumber = 5,
    kArenaSizeFieldNumber = 6,
  };
  // uint64 seed = 1;
  void clear_seed();
  uint64_t seed() const;
  void set_seed(uint64_t value);
  private:
  uint64_t _internal_seed() const;
  void _internal_set_seed(uint64_t value);
  public:

  // uint64 max_steps = 3;
  void clear_max_steps();
  uint64_t max_steps() const;
  void set_max_steps(uint64_t value);
  private:
  uint64_t _internal_max_steps() const;
  void _internal_set_max_steps(uint64_t value);
  public:

  // uint32 num_drones = 2;
  void clear_num_drones();
  uint32_t num_drones() const;
  void set_num_drones(uint32_t value);
  private:
  uint32_t _internal_num_drones() const;
  void _internal_set_num_drones(uint32_t value);
  public:

  // float dt = 4;
  void clear_dt();
  float dt() const;
  void set_dt(float value);
  private:
  float _internal_dt() const;
  void _internal_set_dt(float value);
  public:

  // bool randomize_initial_positions = 5;
  void clear_randomize_initial_positions();
  bool randomize_initial_positions() const;
  void set_randomize_initial_positions(bool value);
  private:
  bool _internal_randomize_initial_positions() const;
  void _internal_set_randomize_initial_positions(bool value);
  public:

  // float arena_size = 6;
  void clear_arena_size();
  float arena_size() const;
  void set_arena_size(float value);
  private:
  float _internal_arena_size() const;
  void _internal_set_arena_size(float value);
  public:

  // @@protoc_insertion_point(class_scope:swarm_proto.ResetRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t seed_;
    uint64_t max_steps_;
    uint32_t num_drones_;
    float dt_;
    bool randomize_initial_positions_;
    float arena_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_swarm_2eproto;
};
// -------------------------------------------------------------------

class ResetResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:swarm_proto.ResetResponse) */ {
 public:
  inline ResetResponse() : ResetResponse(nullptr) {}
  ~ResetResponse() override;
  explicit PROTOBUF_CONSTEXPR ResetResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ResetResponse(const ResetResponse& from);
  ResetResponse(ResetResponse&& from) noexcept
    : ResetResponse() {
    *this = ::std::move(from);
  }

  inline ResetResponse& operator=(const ResetResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResetResponse& operator=(ResetResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResetResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResetResponse* internal_default_instance() {
    return reinterpret_cast<const ResetResponse*>(
               &_ResetResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(ResetResponse& a, ResetResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ResetResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResetResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResetResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ResetResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ResetResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ResetResponse& from) {
    ResetResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResetResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "swarm_proto.ResetResponse";
  }
  protected:
  explicit ResetResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObservationsFieldNumber = 5,
    kStepFieldNumber = 1,
    kMaxStepsFieldNumber = 3,
    kNumDronesFieldNumber = 2,
    kDtFieldNumber = 4,
  };
  // repeated .swarm_proto.DroneObservation observations = 5;
  int observations_size() const;
  private:
  int _internal_observations_size() const;
  public:
  void clear_observations();
  ::swarm_proto::DroneObservation* mutable_observations(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::swarm_proto::DroneObservation >*
      mutable_observations();
  private:
  const ::swarm_proto::DroneObservation& _internal_observations(int index) const;
  ::swarm_proto::DroneObservation* _internal_add_observations();
  public:
  const ::swarm_proto::DroneObservation& observations(int index) const;
  ::swarm_proto::DroneObservation* add_observations();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::swarm_proto::DroneObservation >&
      observations() const;

  // uint64 step = 1;
  void clear_step();
  uint64_t step() const;
  void set_step(uint64_t value);
  private:
  uint64_t _internal_step() const;
  void _internal_set_step(uint64_t value);
  public:

  // uint64 max_steps = 3;
  void clear_max_steps();
  uint64_t max_steps() const;
  void set_max_steps(uint64_t value);
  private:
  uint64_t _internal_max_steps() const;
  void _internal_set_max_steps(uint64_t value);
  public:

  // uint32 num_drones = 2;
  void clear_num_drones();
  uint32_t num_drones() const;
  void set_num_drones(uint32_t value);
  private:
  uint32_t _internal_num_drones() const;
  void _internal_set_num_drones(uint32_t value);
  public:

  // float dt = 4;
  void clear_dt();
  float dt() const;
  void set_dt(float value);
  private:
  float _internal_dt() const;
  void _internal_set_dt(float value);
  public:

  // @@protoc_insertion_point(class_scope:swarm_proto.ResetResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::swarm_proto::DroneObservation > observations_;
    uint64_t step_;
    uint64_t max_steps_;
    uint32_t num_drones_;
    float dt_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_swarm_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DroneAction

// float ax = 1;
inline void DroneAction::clear_ax() {
  _impl_.ax_ = 0;
}
inline float DroneAction::_internal_ax() const {
  return _impl_.ax_;
}
inline float DroneAction::ax() const {
  // @@protoc_insertion_point(field_get:swarm_proto.DroneAction.ax)
  return _internal_ax();
}
inline void DroneAction::_internal_set_ax(float value) {
  
  _impl_.ax_ = value;
}
inline void DroneAction::set_ax(float value) {
  _internal_set_ax(value);
  // @@protoc_insertion_point(field_set:swarm_proto.DroneAction.ax)
}

// float ay = 2;
inline void DroneAction::clear_ay() {
  _impl_.ay_ = 0;
}
inline float DroneAction::_internal_ay() const {
  return _impl_.ay_;
}
inline float DroneAction::ay() const {
  // @@protoc_insertion_point(field_get:swarm_proto.DroneAction.ay)
  return _internal_ay();
}
inline void DroneAction::_internal_set_ay(float value) {
  
  _impl_.ay_ = value;
}
inline void DroneAction::set_ay(float value) {
  _internal_set_ay(value);
  // @@protoc_insertion_point(field_set:swarm_proto.DroneAction.ay)
}

// float az = 3;
inline void DroneAction::clear_az() {
  _impl_.az_ = 0;
}
inline float DroneAction::_internal_az() const {
  return _impl_.az_;
}
inline float DroneAction::az() const {
  // @@protoc_insertion_point(field_get:swarm_proto.DroneAction.az)
  return _internal_az();
}
inline void DroneAction::_internal_set_az(float value) {
  
  _impl_.az_ = value;
}
inline void DroneAction::set_az(float value) {
  _internal_set_az(value);
  // @@protoc_insertion_point(field_set:swarm_proto.DroneAction.az)
}

// -------------------------------------------------------------------

// DroneObservation

// float ox = 1;
inline void DroneObservation::clear_ox() {
  _impl_.ox_ = 0;
}
inline float DroneObservation::_internal_ox() const {
  return _impl_.ox_;
}
inline float DroneObservation::ox() const {
  // @@protoc_insertion_point(field_get:swarm_proto.DroneObservation.ox)
  return _internal_ox();
}
inline void DroneObservation::_internal_set_ox(float value) {
  
  _impl_.ox_ = value;
}
inline void DroneObservation::set_ox(float value) {
  _internal_set_ox(value);
  // @@protoc_insertion_point(field_set:swarm_proto.DroneObservation.ox)
}

// float oy = 2;
inline void DroneObservation::clear_oy() {
  _impl_.oy_ = 0;
}
inline float DroneObservation::_internal_oy() const {
  return _impl_.oy_;
}
inline float DroneObservation::oy() const {
  // @@protoc_insertion_point(field_get:swarm_proto.DroneObservation.oy)
  return _internal_oy();
}
inline void DroneObservation::_internal_set_oy(float value) {
  
  _impl_.oy_ = value;
}
inline void DroneObservation::set_oy(float value) {
  _internal_set_oy(value);
  // @@protoc_insertion_point(field_set:swarm_proto.DroneObservation.oy)
}

// float oz = 3;
inline void DroneObservation::clear_oz() {
  _impl_.oz_ = 0;
}
inline float DroneObservation::_internal_oz() const {
  return _impl_.oz_;
}
inline float DroneObservation::oz() const {
  // @@protoc_insertion_point(field_get:swarm_proto.DroneObservation.oz)
  return _internal_oz();
}
inline void DroneObservation::_internal_set_oz(float value) {
  
  _impl_.oz_ = value;
}
inline void DroneObservation::set_oz(float value) {
  _internal_set_oz(value);
  // @@protoc_insertion_point(field_set:swarm_proto.DroneObservation.oz)
}

// uint32 collision_count = 4;
inline void DroneObservation::clear_collision_count() {
  _impl_.collision_count_ = 0u;
}
inline uint32_t DroneObservation::_internal_collision_count() const {
  return _impl_.collision_count_;
}
inline uint32_t DroneObservation::collision_count() const {
  // @@protoc_insertion_point(field_get:swarm_proto.DroneObservation.collision_count)
  return _internal_collision_count();
}
inline void DroneObservation::_internal_set_collision_count(uint32_t value) {
  
  _impl_.collision_count_ = value;
}
inline void DroneObservation::set_collision_count(uint32_t value) {
  _internal_set_collision_count(value);
  // @@protoc_insertion_point(field_set:swarm_proto.DroneObservation.collision_count)
}

// -------------------------------------------------------------------

// StepRequest

// uint64 step = 1;
inline void StepRequest::clear_step() {
  _impl_.step_ = uint64_t{0u};
}
inline uint64_t StepRequest::_internal_step() const {
  return _impl_.step_;
}
inline uint64_t StepRequest::step() const {
  // @@protoc_insertion_point(field_get:swarm_proto.StepRequest.step)
  return _internal_step();
}
inline void StepRequest::_internal_set_step(uint64_t value) {
  
  _impl_.step_ = value;
}
inline void StepRequest::set_step(uint64_t value) {
  _internal_set_step(value);
  // @@protoc_insertion_point(field_set:swarm_proto.StepRequest.step)
}

// repeated .swarm_proto.DroneAction actions = 2;
inline int StepRequest::_internal_actions_size() const {
  return _impl_.actions_.size();
}
inline int StepRequest::actions_size() const {
  return _internal_actions_size();
}
inline void StepRequest::clear_actions() {
  _impl_.actions_.Clear();
}
inline ::swarm_proto::DroneAction* StepRequest::mutable_actions(int index) {
  // @@protoc_insertion_point(field_mutable:swarm_proto.StepRequest.actions)
  return _impl_.actions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::swarm_proto::DroneAction >*
StepRequest::mutable_actions() {
  // @@protoc_insertion_point(field_mutable_list:swarm_proto.StepRequest.actions)
  return &_impl_.actions_;
}
inline const ::swarm_proto::DroneAction& StepRequest::_internal_actions(int index) const {
  return _impl_.actions_.Get(index);
}
inline const ::swarm_proto::DroneAction& StepRequest::actions(int index) const {
  // @@protoc_insertion_point(field_get:swarm_proto.StepRequest.actions)
  return _internal_actions(index);
}
inline ::swarm_proto::DroneAction* StepRequest::_internal_add_actions() {
  return _impl_.actions_.Add();
}
inline ::swarm_proto::DroneAction* StepRequest::add_actions() {
  ::swarm_proto::DroneAction* _add = _internal_add_actions();
  // @@protoc_insertion_point(field_add:swarm_proto.StepRequest.actions)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::swarm_proto::DroneAction >&
StepRequest::actions() const {
  // @@protoc_insertion_point(field_list:swarm_proto.StepRequest.actions)
  return _impl_.actions_;
}

// -------------------------------------------------------------------

// StepResponse

// uint64 step = 1;
inline void StepResponse::clear_step() {
  _impl_.step_ = uint64_t{0u};
}
inline uint64_t StepResponse::_internal_step() const {
  return _impl_.step_;
}
inline uint64_t StepResponse::step() const {
  // @@protoc_insertion_point(field_get:swarm_proto.StepResponse.step)
  return _internal_step();
}
inline void StepResponse::_internal_set_step(uint64_t value) {
  
  _impl_.step_ = value;
}
inline void StepResponse::set_step(uint64_t value) {
  _internal_set_step(value);
  // @@protoc_insertion_point(field_set:swarm_proto.StepResponse.step)
}

// repeated .swarm_proto.DroneObservation observations = 2;
inline int StepResponse::_internal_observations_size() const {
  return _impl_.observations_.size();
}
inline int StepResponse::observations_size() const {
  return _internal_observations_size();
}
inline void StepResponse::clear_observations() {
  _impl_.observations_.Clear();
}
inline ::swarm_proto::DroneObservation* StepResponse::mutable_observations(int index) {
  // @@protoc_insertion_point(field_mutable:swarm_proto.StepResponse.observations)
  return _impl_.observations_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::swarm_proto::DroneObservation >*
StepResponse::mutable_observations() {
  // @@protoc_insertion_point(field_mutable_list:swarm_proto.StepResponse.observations)
  return &_impl_.observations_;
}
inline const ::swarm_proto::DroneObservation& StepResponse::_internal_observations(int index) const {
  return _impl_.observations_.Get(index);
}
inline const ::swarm_proto::DroneObservation& StepResponse::observations(int index) const {
  // @@protoc_insertion_point(field_get:swarm_proto.StepResponse.observations)
  return _internal_observations(index);
}
inline ::swarm_proto::DroneObservation* StepResponse::_internal_add_observations() {
  return _impl_.observations_.Add();
}
inline ::swarm_proto::DroneObservation* StepResponse::add_observations() {
  ::swarm_proto::DroneObservation* _add = _internal_add_observations();
  // @@protoc_insertion_point(field_add:swarm_proto.StepResponse.observations)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::swarm_proto::DroneObservation >&
StepResponse::observations() const {
  // @@protoc_insertion_point(field_list:swarm_proto.StepResponse.observations)
  return _impl_.observations_;
}

// float reward = 3;
inline void StepResponse::clear_reward() {
  _impl_.reward_ = 0;
}
inline float StepResponse::_internal_reward() const {
  return _impl_.reward_;
}
inline float StepResponse::reward() const {
  // @@protoc_insertion_point(field_get:swarm_proto.StepResponse.reward)
  return _internal_reward();
}
inline void StepResponse::_internal_set_reward(float value) {
  
  _impl_.reward_ = value;
}
inline void StepResponse::set_reward(float value) {
  _internal_set_reward(value);
  // @@protoc_insertion_point(field_set:swarm_proto.StepResponse.reward)
}

// bool done = 4;
inline void StepResponse::clear_done() {
  _impl_.done_ = false;
}
inline bool StepResponse::_internal_done() const {
  return _impl_.done_;
}
inline bool StepResponse::done() const {
  // @@protoc_insertion_point(field_get:swarm_proto.StepResponse.done)
  return _internal_done();
}
inline void StepResponse::_internal_set_done(bool value) {
  
  _impl_.done_ = value;
}
inline void StepResponse::set_done(bool value) {
  _internal_set_done(value);
  // @@protoc_insertion_point(field_set:swarm_proto.StepResponse.done)
}

// -------------------------------------------------------------------

// ResetRequest

// uint64 seed = 1;
inline void ResetRequest::clear_seed() {
  _impl_.seed_ = uint64_t{0u};
}
inline uint64_t ResetRequest::_internal_seed() const {
  return _impl_.seed_;
}
inline uint64_t ResetRequest::seed() const {
  // @@protoc_insertion_point(field_get:swarm_proto.ResetRequest.seed)
  return _internal_seed();
}
inline void ResetRequest::_internal_set_seed(uint64_t value) {
  
  _impl_.seed_ = value;
}
inline void ResetRequest::set_seed(uint64_t value) {
  _internal_set_seed(value);
  // @@protoc_insertion_point(field_set:swarm_proto.ResetRequest.seed)
}

// uint32 num_drones = 2;
inline void ResetRequest::clear_num_drones() {
  _impl_.num_drones_ = 0u;
}
inline uint32_t ResetRequest::_internal_num_drones() const {
  return _impl_.num_drones_;
}
inline uint32_t ResetRequest::num_drones() const {
  // @@protoc_insertion_point(field_get:swarm_proto.ResetRequest.num_drones)
  return _internal_num_drones();
}
inline void ResetRequest::_internal_set_num_drones(uint32_t value) {
  
  _impl_.num_drones_ = value;
}
inline void ResetRequest::set_num_drones(uint32_t value) {
  _internal_set_num_drones(value);
  // @@protoc_insertion_point(field_set:swarm_proto.ResetRequest.num_drones)
}

// uint64 max_steps = 3;
inline void ResetRequest::clear_max_steps() {
  _impl_.max_steps_ = uint64_t{0u};
}
inline uint64_t ResetRequest::_internal_max_steps() const {
  return _impl_.max_steps_;
}
inline uint64_t ResetRequest::max_steps() const {
  // @@protoc_insertion_point(field_get:swarm_proto.ResetRequest.max_steps)
  return _internal_max_steps();
}
inline void ResetRequest::_internal_set_max_steps(uint64_t value) {
  
  _impl_.max_steps_ = value;
}
inline void ResetRequest::set_max_steps(uint64_t value) {
  _internal_set_max_steps(value);
  // @@protoc_insertion_point(field_set:swarm_proto.ResetRequest.max_steps)
}

// float dt = 4;
inline void ResetRequest::clear_dt() {
  _impl_.dt_ = 0;
}
inline float ResetRequest::_internal_dt() const {
  return _impl_.dt_;
}
inline float ResetRequest::dt() const {
  // @@protoc_insertion_point(field_get:swarm_proto.ResetRequest.dt)
  return _internal_dt();
}
inline void ResetRequest::_internal_set_dt(float value) {
  
  _impl_.dt_ = value;
}
inline void ResetRequest::set_dt(float value) {
  _internal_set_dt(value);
  // @@protoc_insertion_point(field_set:swarm_proto.ResetRequest.dt)
}

// bool randomize_initial_positions = 5;
inline void ResetRequest::clear_randomize_initial_positions() {
  _impl_.randomize_initial_positions_ = false;
}
inline bool ResetRequest::_internal_randomize_initial_positions() const {
  return _impl_.randomize_initial_positions_;
}
inline bool ResetRequest::randomize_initial_positions() const {
  // @@protoc_insertion_point(field_get:swarm_proto.ResetRequest.randomize_initial_positions)
  return _internal_randomize_initial_positions();
}
inline void ResetRequest::_internal_set_randomize_initial_positions(bool value) {
  
  _impl_.randomize_initial_positions_ = value;
}
inline void ResetRequest::set_randomize_initial_positions(bool value) {
  _internal_set_randomize_initial_positions(value);
  // @@protoc_insertion_point(field_set:swarm_proto.ResetRequest.randomize_initial_positions)
}

// float arena_size = 6;
inline void ResetRequest::clear_arena_size() {
  _impl_.arena_size_ = 0;
}
inline float ResetRequest::_internal_arena_size() const {
  return _impl_.arena_size_;
}
inline float ResetRequest::arena_size() const {
  // @@protoc_insertion_point(field_get:swarm_proto.ResetRequest.arena_size)
  return _internal_arena_size();
}
inline void ResetRequest::_internal_set_arena_size(float value) {
  
  _impl_.arena_size_ = value;
}
inline void ResetRequest::set_arena_size(float value) {
  _internal_set_arena_size(value);
  // @@protoc_insertion_point(field_set:swarm_proto.ResetRequest.arena_size)
}

// -------------------------------------------------------------------

// ResetResponse

// uint64 step = 1;
inline void ResetResponse::clear_step() {
  _impl_.step_ = uint64_t{0u};
}
inline uint64_t ResetResponse::_internal_step() const {
  return _impl_.step_;
}
inline uint64_t ResetResponse::step() const {
  // @@protoc_insertion_point(field_get:swarm_proto.ResetResponse.step)
  return _internal_step();
}
inline void ResetResponse::_internal_set_step(uint64_t value) {
  
  _impl_.step_ = value;
}
inline void ResetResponse::set_step(uint64_t value) {
  _internal_set_step(value);
  // @@protoc_insertion_point(field_set:swarm_proto.ResetResponse.step)
}

// uint32 num_drones = 2;
inline void ResetResponse::clear_num_drones() {
  _impl_.num_drones_ = 0u;
}
inline uint32_t ResetResponse::_internal_num_drones() const {
  return _impl_.num_drones_;
}
inline uint32_t ResetResponse::num_drones() const {
  // @@protoc_insertion_point(field_get:swarm_proto.ResetResponse.num_drones)
  return _internal_num_drones();
}
inline void ResetResponse::_internal_set_num_drones(uint32_t value) {
  
  _impl_.num_drones_ = value;
}
inline void ResetResponse::set_num_drones(uint32_t value) {
  _internal_set_num_drones(value);
  // @@protoc_insertion_point(field_set:swarm_proto.ResetResponse.num_drones)
}

// uint64 max_steps = 3;
inline void ResetResponse::clear_max_steps() {
  _impl_.max_steps_ = uint64_t{0u};
}
inline uint64_t ResetResponse::_internal_max_steps() const {
  return _impl_.max_steps_;
}
inline uint64_t ResetResponse::max_steps() const {
  // @@protoc_insertion_point(field_get:swarm_proto.ResetResponse.max_steps)
  return _internal_max_steps();
}
inline void ResetResponse::_internal_set_max_steps(uint64_t value) {
  
  _impl_.max_steps_ = value;
}
inline void ResetResponse::set_max_steps(uint64_t value) {
  _internal_set_max_steps(value);
  // @@protoc_insertion_point(field_set:swarm_proto.ResetResponse.max_steps)
}

// float dt = 4;
inline void ResetResponse::clear_dt() {
  _impl_.dt_ = 0;
}
inline float ResetResponse::_internal_dt() const {
  return _impl_.dt_;
}
inline float ResetResponse::dt() const {
  // @@protoc_insertion_point(field_get:swarm_proto.ResetResponse.dt)
  return _internal_dt();
}
inline void ResetResponse::_internal_set_dt(float value) {
  
  _impl_.dt_ = value;
}
inline void ResetResponse::set_dt(float value) {
  _internal_set_dt(value);
  // @@protoc_insertion_point(field_set:swarm_proto.ResetResponse.dt)
}

// repeated .swarm_proto.DroneObservation observations = 5;
inline int ResetResponse::_internal_observations_size() const {
  return _impl_.observations_.size();
}
inline int ResetResponse::observations_size() const {
  return _internal_observations_size();
}
inline void ResetResponse::clear_observations() {
  _impl_.observations_.Clear();
}
inline ::swarm_proto::DroneObservation* ResetResponse::mutable_observations(int index) {
  // @@protoc_insertion_point(field_mutable:swarm_proto.ResetResponse.observations)
  return _impl_.observations_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::swarm_proto::DroneObservation >*
ResetResponse::mutable_observations() {
  // @@protoc_insertion_point(field_mutable_list:swarm_proto.ResetResponse.observations)
  return &_impl_.observations_;
}
inline const ::swarm_proto::DroneObservation& ResetResponse::_internal_observations(int index) const {
  return _impl_.observations_.Get(index);
}
inline const ::swarm_proto::DroneObservation& ResetResponse::observations(int index) const {
  // @@protoc_insertion_point(field_get:swarm_proto.ResetResponse.observations)
  return _internal_observations(index);
}
inline ::swarm_proto::DroneObservation* ResetResponse::_internal_add_observations() {
  return _impl_.observations_.Add();
}
inline ::swarm_proto::DroneObservation* ResetResponse::add_observations() {
  ::swarm_proto::DroneObservation* _add = _internal_add_observations();
  // @@protoc_insertion_point(field_add:swarm_proto.ResetResponse.observations)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::swarm_proto::DroneObservation >&
ResetResponse::observations() const {
  // @@protoc_insertion_point(field_list:swarm_proto.ResetResponse.observations)
  return _impl_.observations_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace swarm_proto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_swarm_2eproto
